### ISSUE TITLE
Missing nugets?

### ISSUE THREAD

**Issue by Crypties** [CaptainPStar/AIAssistant#9]
There seems to be missing nugets references in the .csproj. E.g. Search Pioneer API, Milvus, Flurl.
I'll clone again using a different method. This was with "Open using Visual Studio". 

Update #1: Same using GitHub Desktop for Windows.

**Comment by CaptainPStar** [comment]
Should be resolved. I removed the Memory feature a while ago and I assume the references got back in when I moved between computers.
